"""Builds every Bucks brand asset from letters.json (made by trace_logo.py). Re-run after re-tracing:
    python3 branding/trace_logo.py <logo.jpg> && python3 branding/generate_assets.py
Outputs: Android vector drawables (launcher icon, monochrome icon, wordmark, notification icon), the Kotlin path data the
splash motion and loader animate, and Play Store PNGs (512 icon, 1024x500 feature graphic)."""
import json, re, os, io
import cairosvg
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
RES = os.path.join(ROOT, 'app/src/main/res'); KT = os.path.join(ROOT, 'app/src/main/java/com/bucks/app/ui/components/BrandPaths.kt')
PURPLE = '#811FF0'
data = json.load(open(os.path.join(HERE, 'letters.json')))
x0, y0, x1, y1 = data['box']; W, H = x1 - x0, y1 - y0
PAIR = re.compile(r'(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)')
def shift(d, dx, dy):
    return PAIR.sub(lambda m: f"{round(float(m.group(1)) - dx, 2):g},{round(float(m.group(2)) - dy, 2):g}", d)
letters = [{'d': shift(l['d'], x0, y0), 'bb': [l['bb'][0] - x0, l['bb'][1] - y0, l['bb'][2] - x0, l['bb'][3] - y0]} for l in data['letters']]
word_d = ''.join(l['d'] for l in letters)
names = ['b', 'u', 'c', 'k', 's']

def write(path, text): os.makedirs(os.path.dirname(path), exist_ok=True); open(path, 'w').write(text)
def vector(w_dp, h_dp, vw, vh, body): return (f'<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by branding/generate_assets.py; do not edit by hand. -->\n'
    f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{w_dp}dp" android:height="{h_dp}dp" android:viewportWidth="{vw:g}" android:viewportHeight="{vh:g}">\n{body}</vector>\n')
def group(scale, tx, ty, d, color='#FFFFFF'): return (f'  <group android:scaleX="{scale:.6f}" android:scaleY="{scale:.6f}" android:translateX="{tx:.3f}" android:translateY="{ty:.3f}">\n'
    f'    <path android:fillColor="{color}" android:fillType="evenOdd" android:pathData="{d}"/>\n  </group>\n')

# ---- launcher: 108dp adaptive canvas, wordmark 58dp wide centred (inside the 66dp safe circle, with room to breathe on round masks)
ICON_W = 58.0; s = ICON_W / W; tx = (108 - W * s) / 2; ty = (108 - H * s) / 2 + 1.0   # +1dp: optical centre (the b's ascender lifts the mass)
fg = vector(108, 108, 108, 108, group(s, tx, ty, word_d))
write(f'{RES}/drawable/ic_launcher_foreground.xml', fg)
write(f'{RES}/drawable/ic_launcher_monochrome.xml', fg)
write(f'{RES}/values/colors.xml', f'<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="bucks_purple">{PURPLE}</color>\n    <color name="ic_launcher_background">{PURPLE}</color>\n</resources>\n')
write(f'{RES}/mipmap-anydpi/ic_launcher.xml', '<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
      '    <background android:drawable="@color/ic_launcher_background"/>\n    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
      '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n</adaptive-icon>\n')

# ---- wordmark drawable (white; tint it where it sits on a light surface)
write(f'{RES}/drawable/bucks_wordmark.xml', vector(round(40 * W / H, 1), 40, W, H, f'  <path android:fillColor="#FFFFFF" android:fillType="evenOdd" android:pathData="{word_d}"/>\n'))

# ---- notification icon: the "b", 24dp, white silhouette with 2dp padding
b = letters[0]; bw, bh = b['bb'][2] - b['bb'][0], b['bb'][3] - b['bb'][1]; sb = 20.0 / bh
write(f'{RES}/drawable/ic_stat_bucks.xml', vector(24, 24, 24, 24, group(sb, (24 - bw * sb) / 2 - b['bb'][0] * sb, 2 - b['bb'][1] * sb, b['d'])))

# ---- splash: the system splash is only the purple field; the motion itself is drawn by Compose (BrandIntro)
write(f'{RES}/drawable/splash_blank.xml', '<?xml version="1.0" encoding="utf-8"?>\n<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">\n    <solid android:color="@android:color/transparent"/>\n</shape>\n')

# ---- Kotlin path data for Compose (animated per letter)
kt = ['// Generated by branding/generate_assets.py from the traced logo; do not edit by hand.', 'package com.bucks.app.ui.components', '',
      '/** The Bucks wordmark as vector paths, one per letter, in a %.1f x %.1f box (origin top-left). */' % (W, H),
      'internal object BrandPaths {', f'    const val WIDTH = {W:.2f}f', f'    const val HEIGHT = {H:.2f}f',
      '    /** Letters left to right: b, u, c, k, s. [bounds] is left, top, right, bottom in the same units. */',
      '    val letters: List<Pair<String, FloatArray>> = listOf(']
for n, l in zip(names, letters):
    kt.append(f'        // {n}\n        "{l["d"]}" to floatArrayOf({", ".join(f"{v:.2f}f" for v in l["bb"])}),')
kt += ['    )', '}', '']
write(KT, '\n'.join(kt))

# ---- master SVGs + Play Store PNGs
def svg(w, h, bg, scale, tx, ty, fill='#FFFFFF'):
    r = f'<rect width="{w}" height="{h}" fill="{bg}"/>' if bg else ''
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">{r}<g transform="translate({tx:.3f} {ty:.3f}) scale({scale:.6f})"><path fill="{fill}" fill-rule="evenodd" d="{word_d}"/></g></svg>'
write(f'{HERE}/bucks_wordmark_white.svg', svg(round(W, 2), round(H, 2), None, 1, 0, 0))
write(f'{HERE}/bucks_wordmark_purple.svg', svg(round(W, 2), round(H, 2), None, 1, 0, 0, PURPLE))
sq = 1080 * 0.72 / W; write(f'{HERE}/bucks_logo_square.svg', svg(1080, 1080, PURPLE, sq, (1080 - W * sq) / 2, (1080 - H * sq) / 2))
def png(svgtext, path, w, h): Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svgtext.encode(), output_width=w, output_height=h))).convert('RGB').save(path, optimize=True)
ps = 512 * 0.62 / W; png(svg(512, 512, PURPLE, ps, (512 - W * ps) / 2, (512 - H * ps) / 2 + 512 / 108), f'{HERE}/play_store_icon_512.png', 512, 512)
fs = 1024 * 0.46 / W; png(svg(1024, 500, PURPLE, fs, (1024 - W * fs) / 2, (500 - H * fs) / 2), f'{HERE}/play_feature_graphic_1024x500.png', 1024, 500)
png(svg(1080, 1080, PURPLE, sq, (1080 - W * sq) / 2, (1080 - H * sq) / 2), f'{HERE}/bucks_logo_2160.png', 2160, 2160)
print('ok', round(W, 2), round(H, 2))
