package com.bucks.app.ui.components

import android.app.Activity
import androidx.compose.animation.core.Animatable
import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.spring
import androidx.compose.animation.core.tween
import androidx.compose.animation.core.animateFloat
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.size
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.BlendMode
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.CompositingStrategy
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.drawscope.scale
import androidx.compose.ui.graphics.drawscope.translate
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalView
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.core.view.WindowCompat
import com.bucks.app.ui.theme.Purple
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.math.PI
import kotlin.math.sin

/*
 * The Bucks wordmark, drawn from the traced logo (BrandPaths, generated by branding/generate_assets.py) so it stays sharp
 * at any size and each letter can move on its own. Three uses:
 *  - BucksWordmark: the static mark (top bar, online button, anywhere the brand name shows).
 *  - BucksLoader:   the letters ripple like a wave; replaces the page-level spinners.
 *  - WordmarkEntrance + BrandIntro: the launch motion (letters spring up one after another, then a light sweeps across).
 * With "Remove animations" or the app's Reduce motion setting on, nothing moves: the mark simply appears.
 */

/** How one letter is drawn at a moment: [dy] in wordmark heights (negative = up), scales about the letter's baseline centre. */
class LetterPose(val dy: Float = 0f, val scaleX: Float = 1f, val scaleY: Float = 1f, val alpha: Float = 1f) {
    companion object { val Rest = LetterPose() }
}

private class Letter(val path: Path, val bounds: Rect)
private val letters: List<Letter> by lazy {
    BrandPaths.letters.map { (d, b) -> Letter(PathParser().parsePathString(d).toPath().apply { fillType = PathFillType.EvenOdd }, Rect(b[0], b[1], b[2], b[3])) }
}

/**
 * The wordmark at [height] (its width follows the logo's proportions). [pose] is read while drawing, so an animation that
 * changes it redraws without recomposing. [sheen] is where a light band crosses the letters (0..1), or negative for none.
 */
@Composable
fun BucksWordmark(
    modifier: Modifier = Modifier, height: Dp = 28.dp, color: Color = MaterialTheme.colorScheme.primary, contentDescription: String? = "Bucks",
    sheen: () -> Float = { -1f }, pose: (Int) -> LetterPose = { LetterPose.Rest },
    /** The sweep has to differ from the letters to show: a lavender glint on white letters, white on coloured ones. */
    sheenColor: Color = if (color.luminance() > 0.5f) Color(0xFFBE98FF) else Color.White,
) {
    val width = height * (BrandPaths.WIDTH / BrandPaths.HEIGHT)
    val a11y = if (contentDescription != null) Modifier.semantics { this.contentDescription = contentDescription; role = Role.Image } else Modifier
    Canvas(modifier.then(a11y).size(width, height).graphicsLayer { compositingStrategy = CompositingStrategy.Offscreen }) {
        val s = size.height / BrandPaths.HEIGHT
        scale(s, s, pivot = Offset.Zero) {
            letters.forEachIndexed { i, l ->
                val p = pose(i)
                if (p.alpha <= 0f) return@forEachIndexed
                translate(top = p.dy * BrandPaths.HEIGHT) {
                    scale(p.scaleX, p.scaleY, pivot = Offset(l.bounds.center.x, l.bounds.bottom)) { drawPath(l.path, color, alpha = p.alpha.coerceIn(0f, 1f)) }
                }
            }
            val at = sheen()
            if (at >= 0f) {
                // A soft diagonal band of light, drawn only on the letters (SrcAtop over the offscreen layer).
                val w = BrandPaths.WIDTH; val band = w * 0.28f; val x = -band + (w + band * 2) * at
                drawRect(Brush.linearGradient(listOf(sheenColor.copy(alpha = 0f), sheenColor.copy(alpha = 0.85f), sheenColor.copy(alpha = 0f)), start = Offset(x - band, 0f), end = Offset(x, BrandPaths.HEIGHT * 0.6f)),
                    size = androidx.compose.ui.geometry.Size(w, BrandPaths.HEIGHT), blendMode = BlendMode.SrcAtop)
            }
        }
    }
}

/**
 * "Load runner": the letters of the wordmark ripple left to right, each lifting and brightening in turn. Use it where a
 * page or a section is waiting for data; small spinners inside buttons and rows stay as they are (the mark is too wide there).
 */
@Composable
fun BucksLoader(modifier: Modifier = Modifier, height: Dp = 22.dp, color: Color = MaterialTheme.colorScheme.primary, label: String = "Loading") {
    if (rememberReducedMotion()) { BucksWordmark(modifier, height, color.copy(alpha = 0.6f), contentDescription = label); return }
    val phase = rememberInfiniteTransition(label = "loader").animateFloat(0f, 1f, infiniteRepeatable(tween(1150, easing = LinearEasing), RepeatMode.Restart), label = "wave")
    BucksWordmark(modifier, height, color, contentDescription = label) { i ->
        var x = phase.value - i * 0.11f; if (x < 0f) x += 1f
        val bump = if (x < 0.42f) sin(x / 0.42f * PI).toFloat() else 0f
        LetterPose(dy = -0.2f * bump, scaleY = 1f + 0.07f * bump, scaleX = 1f - 0.03f * bump, alpha = 0.5f + 0.5f * bump)
    }
}

/** The launch motion's state: each letter springs up from below the baseline, one after another, then a light sweeps across. */
class WordmarkEntrance {
    private val progress = List(5) { Animatable(0f) }
    val sheen = Animatable(-1f)
    /** About 1.1 s. */
    suspend fun play() = coroutineScope {
        progress.forEachIndexed { i, a -> launch { delay(i * 75L); a.animateTo(1f, spring(dampingRatio = 0.52f, stiffness = 260f)) } }
        launch { delay(560); sheen.snapTo(0f); sheen.animateTo(1f, tween(520, easing = FastOutSlowInEasing)); sheen.snapTo(-1f) }
    }
    suspend fun snapIn() { progress.forEach { it.snapTo(1f) } }
    fun pose(i: Int): LetterPose {
        val p = progress[i].value   // a lively spring overshoots past 1, so letters rise a touch too far and settle back
        return LetterPose(dy = (1f - p) * 0.6f, scaleX = 1f + (1f - p) * 0.12f, scaleY = 0.55f + 0.45f * p, alpha = (p * 1.6f).coerceIn(0f, 1f))
    }
}

/** Light status-bar icons while a purple brand screen is showing; restores the app's dark icons afterwards. */
@Composable
fun LightSystemBars() {
    val view = LocalView.current
    if (view.isInEditMode) return
    DisposableEffect(view) {
        val window = (view.context as? Activity)?.window
        val c = window?.let { WindowCompat.getInsetsController(it, view) }
        val before = c?.isAppearanceLightStatusBars
        c?.isAppearanceLightStatusBars = false; c?.isAppearanceLightNavigationBars = false
        onDispose { if (before != null) { c?.isAppearanceLightStatusBars = before; c?.isAppearanceLightNavigationBars = before } }
    }
}

/**
 * Cold-start intro for people already signed in: the purple system splash hands over to this, the wordmark plays its
 * entrance, then the whole layer fades up into the app (about 1.5 s; a tap skips it). Signed-out people get the same
 * entrance on the welcome screen instead.
 */
@Composable
fun BrandIntro(onDone: () -> Unit) {
    val reduced = rememberReducedMotion(); val done = rememberUpdatedState(onDone)
    val e = remember { WordmarkEntrance() }; val fade = remember { Animatable(1f) }; val zoom = remember { Animatable(1f) }
    LightSystemBars()
    LaunchedEffect(Unit) {
        if (reduced) { e.snapIn(); delay(300); fade.animateTo(0f, tween(180)); done.value(); return@LaunchedEffect }
        e.play(); delay(80)
        coroutineScope { launch { zoom.animateTo(1.1f, tween(340, easing = Motion.Emphasized)) }; fade.animateTo(0f, tween(340, easing = FastOutSlowInEasing)) }
        done.value()
    }
    Box(Modifier.fillMaxSize().graphicsLayer { alpha = fade.value }.background(Purple).pointerInput(Unit) { detectTapGestures { done.value() } }, contentAlignment = Alignment.Center) {
        BucksWordmark(Modifier.graphicsLayer { scaleX = zoom.value; scaleY = zoom.value }, height = 58.dp, color = Color.White, sheen = { e.sheen.value }, pose = e::pose)
    }
}
